changed indents

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -10,35 +10,35 @@ jobs:
       - setup_remote_docker
 
       - run:
-        name: "Build"
-        command: |
-            docker build -t ncar/aws-cli:latest .
-            verstr=`docker --rm ncar/aws-cli --version`
-            version=`expr "${verstr}" : 'aws-cli/\([^ ]*\) .*'`
-            if [ ":${version}" = ":" \ ; then
-                echo "Unable to determine version!"
-                exit 1
-            fi
-            docker tag ncar/aws-cli:latest ncar/aws-cli:${version}
-            docker push
+          name: Build
+          command: |
+              docker build -t ncar/aws-cli:latest .
+              verstr=`docker --rm ncar/aws-cli --version`
+              version=`expr "${verstr}" : 'aws-cli/\([^ ]*\) .*'`
+              if [ ":${version}" = ":" \ ; then
+                  echo "Unable to determine version!"
+                  exit 1
+              fi
+              docker tag ncar/aws-cli:latest ncar/aws-cli:${version}
+              docker push
 
 workflows:
-   version: 2
+    version: 2
 
-   update:
-     jobs:
-       - build
+    update:
+        jobs:
+            - build
 
-   weekly:
-     triggers:
-       - schedule:
-           cron: "0 0 * * 0"
-           filters:
-             branches:
-               only:
-                 - master
-     jobs:
-       - build
+    weekly:
+        triggers:
+            - schedule:
+                cron: "0 0 * * 0"
+                filters:
+                    branches:
+                        only:
+                            - master
+        jobs:
+            - build
 
 
 
